sudo: required
language: cpp
dist: trusty

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6

before_script:

    # install SFML 2.4.2 (not in trusty repositories)
    - wget https://www.sfml-dev.org/files/SFML-2.4.2-linux-gcc-64-bit.tar.gz
    - tar -xf SFML-2.4.2-linux-gcc-64-bit.tar.gz
    - ls
    - sudo cp -r SFML-2.4.2/* /usr/

    - sudo apt-get update
    - sudo apt-get install libopenal1 cmake -y
script: 
    - mkdir build && cd build/
    - cmake -D CMAKE_CXX_COMPILER=g++-6 ..
    - make -j
