#!/bin/bash

RED='\033[0;31m'

# apply style on .cpp and .hpp files
astyle --style=allman src/*.cpp
astyle --style=allman includes/*.hpp

# delete temporary files generated by astyle
find . -name "*.orig" -type f -delete

# check length of lines, should not exceed 80 characters
res=$(grep '.\{80\}' src/*.cpp)$(grep '.\{80\}' includes/*.hpp)
if [[ $res ]]; then
    echo -e "${RED}LINES ARE TOO LONG ( exceed 80 characters )"
    echo "( grep '.\{80\}' src/*.cpp | grep '.\{80\}' includes/*.hpp )"
    exit 1
fi
